---
- name: setup desktop environment
  gather_facts: False
  hosts: localhost
  roles:
    # UI
    - chrome
    - gnome-shell

    # common dev
    - dev
    - xclip
    - cron-update-packages
    - vim
    - tmux
    - fzf

    # languages
    - go

    # virtualization
    - virtualbox

    # kubernetes
    - kube-client
    - k9s
    - helm-client
    - helmfile

    # devops
    - terraform
    - vault
    - packer
    - chef

    # clouds
    - aws
