---
- name: add python repository
  apt_repository:
    repo: ppa:deadsnakes/ppa
  become: True

- name: install python {{ python_version }}
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - python{{ python_version }}
      - python{{ python_version }}-venv
      - python{{ python_version }}-dev
  become: True

- name: create python symlink python3 => python{{ python_version }}
  file:
    src: /usr/bin/python{{ python_version }}
    dest: /usr/bin/python3
    state: link
  become: True

