---
- name: Install git
  apt:
    name: git
    state: present

- name: setup git configs
  blockinfile:
    path: ~/.gitconfig
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    create: True
    block: |
      [alias]
          co = checkout
          br = branch
          st = status
      [pull]
          rebase = true
          default = current
      [user]
          name = Max Murygin
          email = maxim.murygin@booking.com
...
