---
- name: add git aliases
  blockinfile:
    path: ~/.gitconfig
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    create: True
    block: |
      [alias]
        co = checkout
        br = branch
        st = status

- name: setup branch name
  blockinfile:
    path: ~/.bashrc
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: "{{ lookup('file', './files/branch-name.sh') }}"
...
