---
- name: add python repository
  apt_repository:
    repo: ppa:deadsnakes/ppa
  become: True

- name: install python {{ python_version }}
  apt:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - python{{ python_version }}
      - python{{ python_version }}-venv
      - python{{ python_version }}-dev
  become: True

- name: add alias
  lineinfile:
    path: ~/.bashrc
    state: present
    line: 'alias venv="python3.8 -m venv .venv && source .venv/bin/activate && pip install --upgrade pip"'
