- name: install dependencies to build tmux
  apt:
    name:
      - build-essential
      - libevent-dev
      - libncurses5-dev
      - libncursesw5-dev
    state: present
  become: true

- name: Download tmux binary
  get_url:
    url: https://github.com/tmux/tmux/releases/download/{{ tmux_version }}/tmux-{{ tmux_version }}.tar.gz
    dest: /tmp/tmux.tar.gz

- name: Extract tmux
  unarchive:
    src: /tmp/tmux.tar.gz
    dest: /tmp

- name: Configure tmux before installation
  command: ./configure
  args:
    chdir: /tmp/tmux-{{ tmux_version }}

- name: Build tmux
  make:
    chdir: /tmp/tmux-{{ tmux_version }}

- name: Install tmux
  shell: make install
  args:
    chdir: /tmp/tmux-{{ tmux_version }}
  become: true

- name: Remove downloaded archive
  file:
    path: /tmp/tmux.tar.gz
    state: absent

- name: Remove tmp dir
  file:
    path: /tmp/tmux-{{ tmux_version }}
    state: absent
