- name: create bundle directory
  file:
    path: ~/.vim/bundle
    state: directory

- name: install vundle
  git:
    repo: https://github.com/VundleVim/Vundle.vim.git
    dest: ~/.vim/bundle/Vundle.vim
    update: no

- name: install plugins
  command: vim +PluginInstall +qall
  changed_when: no
