- name: create autoload directory
  file:
    path: ~/.vim/autoload
    state: directory

- name: install vim-plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.vim/autoload/plug.vim

- name: install plugins
  command: vim +PlugInstall +qall
  changed_when: no
